// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcixivlrcgzyctuqahia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjaXhpdmxyY2d6eWN0dXFhaGlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNjcyNTcsImV4cCI6MjA2ODk0MzI1N30.lTnWLlFVO9I04WEbb_CFZSOTIefg50iFj1Z3G6EVyks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});